### ISSUE TITLE
wrong ELF class: ELFCLASS64

### ISSUE THREAD

**Issue by madratman** [warp1337/rosleapmotion#5]
youbot@youbot-desktop:~/Downloads/Leap_Motion_Installer_Packages_release_public_linux$ source ~/catkin_ws/devel/setup.bash && rosrun leap_motion sender.py
Traceback (most recent call last):
  File "/home/youbot/catkin_ws/src/rosleapmotion/scripts/sender.py", line 4, in <module>
    import leap_interface
  File "/home/youbot/catkin_ws/src/rosleapmotion/scripts/leap_interface.py", line 26, in <module>
    import Leap
  File "/home/youbot/Downloads/LeapDeveloperKit/LeapSDK/lib/Leap.py", line 26, in <module>
    LeapPython = swig_import_helper()
  File "/home/youbot/Downloads/LeapDeveloperKit/LeapSDK/lib/Leap.py", line 18, in swig_import_helper
    import LeapPython
ImportError: /home/youbot/Downloads/LeapDeveloperKit/LeapSDK/lib/x64/LeapPython.so: wrong ELF class: ELFCLASS64
youbot@youbot-desktop:~/Downloads/Leap_Motion_Installer_Packages_release_public_linux$

**Comment by warp1337** [comment]
Are you on 32 bit? I guess you need to download the 32 bit version of the SDK

**Comment by warp1337** [comment]
_bump_
